### ISSUE TITLE
Replace favicon with svg

### ISSUE THREAD

**Issue by tom-ai** [tom-ai/song-list#4]
I think it's better to use a sag as the favicon rather than a `.ico`. Find a similar SVG icon of a violin and update accordingly.

**Comment by hannahro15** [comment]
Should this issue be closed now?

**Comment by tom-ai** [comment]
Yes can be closed 👍On 26 Dec 2024, at 22:49, Hannah Olbrich ***@***.***> wrote:﻿
Should this issue be closed now?

**Comment by hannahro15** [comment]
Yup! It should be closed now!
