### ISSUE TITLE
Show list of all songs if a search returns no results

### ISSUE THREAD

**Issue by tom-ai** [tom-ai/song-list#8]
Currently, if I search for a song and it's not in the list I see no results. That may seem logical, but as a user I think I'd rather just see all the songs available rather than nothing.

<img width="1114" alt="Screenshot 2024-11-24 at 23 04 37" src="https://github.com/user-attachments/assets/030930c2-c5bf-43c1-a025-f09eef7ea50e">

**Comment by hannahro15** [comment]
I think having it as 'No songs found matching "....."' is better for the user experience. That would be my preference as I would want to know if a particular song wasn't available in the song list.

**Comment by tom-ai** [comment]
Fair enough
